from typing import Dict, Any, List, Optional
from app.schemas.ai_schema import Task, TaskResult, Citation
from app.ai_system.orchestrator.constants import (
    TASK_CHAT_ANSWER,
    TASK_EXPLAIN,
    TASK_SUMMARY,
    TASK_QUIZ,
    TASK_ANSWER_TABLE,
    TASK_KEY_POINTS,
    TASK_COMPARISON_TABLE,
    NO_ANSWER_FALLBACK
)

# Mock confidence level as requested (not high confidence for mock outputs)
MOCK_CONFIDENCE = 0.5

def check_no_answer_trigger(query: str) -> bool:
    """Checks if query simulates requesting information outside the document context."""
    normalized = query.lower()
    return "خارج الملف" in normalized or "outside the file" in normalized

async def run_chat_answer_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """Simulates localized QA search pipeline using vector chunks (top-k)."""
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_CHAT_ANSWER,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    if lang == "ar":
        content = f"هذا جواب محاكاة لسؤالك: '{task.query}' استناداً إلى محتوى الملف."
    else:
        content = f"This is a simulated answer to your question: '{task.query}' grounded strictly in the document."

    return TaskResult(
        task_id=task.task_id,
        type=TASK_CHAT_ANSWER,
        status="success",
        content=content,
        citations=[Citation(chunk_id="chunk_chat_1", page_number=1, score=0.85)],
        confidence=MOCK_CONFIDENCE,
        metadata={"mock": True, "pipeline": "vector_chat_top_k"}
    )

async def run_explain_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """Simulates explanation pipeline for a targeted segment."""
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_EXPLAIN,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    if lang == "ar":
        content = f"شرح مفصل ومبسط للفقرة المطلوبة: '{task.query}'. تم توضيح النقاط الأساسية بلغة واضحة."
    else:
        content = f"Detailed explanation for: '{task.query}'. The core points have been clarified in simple terms."

    return TaskResult(
        task_id=task.task_id,
        type=TASK_EXPLAIN,
        status="success",
        content=content,
        citations=[Citation(chunk_id="chunk_explain_1", page_number=2, score=0.88)],
        confidence=MOCK_CONFIDENCE,
        metadata={"mock": True, "pipeline": "explanation_generator"}
    )

async def run_summary_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """
    Simulates document-level summary.
    Designed as a document-level task that utilizes all chunks/representative chunks.
    """
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_SUMMARY,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    style = getattr(request, "summary_style", "bullet_points") or "bullet_points"
    
    # Document-level context flag simulation (uses representative chunks)
    meta = {
        "mock": True,
        "context_level": "document",
        "chunks_processed": "all",
        "summary_style": style
    }

    if lang == "ar":
        content = "### ملخص المستند الشامل\n- الفكرة الأولى: هذا ملخص تم إنشاؤه عبر معالجة جميع أجزاء الملف.\n- الفكرة الثانية: تنظيم وهيكلة ممتازة للمفاهيم التعليمية.\n- الفكرة الثالثة: توافق الأهداف التعليمية مع مستويات الطلاب."
    else:
        content = "### Document Comprehensive Summary\n- Core Idea 1: This summary is generated by processing all chunks of the document.\n- Core Idea 2: Structured organization of educational concepts.\n- Core Idea 3: Alignment of learning objectives with user profiles."

    return TaskResult(
        task_id=task.task_id,
        type=TASK_SUMMARY,
        status="success",
        content=content,
        citations=[
            Citation(chunk_id="chunk_doc_start", page_number=1, score=0.90),
            Citation(chunk_id="chunk_doc_middle", page_number=5, score=0.85),
            Citation(chunk_id="chunk_doc_end", page_number=10, score=0.80)
        ],
        confidence=MOCK_CONFIDENCE,
        metadata=meta
    )

async def run_quiz_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """
    Simulates document-level quiz generator.
    Designed as a document-level task utilizing all chunks to build questions.
    """
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_QUIZ,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    diff = getattr(request, "difficulty", "medium") or "medium"
    num_q = getattr(request, "number_of_questions", 3) or 3

    meta = {
        "mock": True,
        "context_level": "document",
        "chunks_processed": "all",
        "difficulty": diff,
        "number_of_questions": num_q,
        # Save generated questions inside task metadata for sequential consumption
        "generated_questions": [
            {"id": "q1", "question": "ما عاصمة مصر؟" if lang == "ar" else "What is the capital of Egypt?", "options": ["القاهرة", "الإسكندرية"] if lang == "ar" else ["Cairo", "Alexandria"], "correct": "القاهرة" if lang == "ar" else "Cairo"},
            {"id": "q2", "question": "ما الصيغة الكيميائية للماء؟" if lang == "ar" else "What is the chemical formula of water?", "options": ["H2O", "CO2"], "correct": "H2O"}
        ]
    }

    if lang == "ar":
        content = "### اختبار محاكاة (مستوى: {})\n1. ما عاصمة مصر؟\n2. ما الصيغة الكيميائية للماء؟".format(diff)
    else:
        content = "### Simulated Quiz (Level: {})\n1. What is the capital of Egypt?\n2. What is the chemical formula of water?".format(diff)

    return TaskResult(
        task_id=task.task_id,
        type=TASK_QUIZ,
        status="success",
        content=content,
        citations=[
            Citation(chunk_id="chunk_quiz_source_1", page_number=2, score=0.92),
            Citation(chunk_id="chunk_quiz_source_2", page_number=4, score=0.91)
        ],
        confidence=MOCK_CONFIDENCE,
        metadata=meta
    )

async def run_answer_table_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """Simulates generating an answer table. Consumes outputs from dependent quiz task if sequential execution."""
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_ANSWER_TABLE,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    
    # Retrieve questions generated by previous task if it was sequential
    questions = []
    if previous_results:
        for t_res in previous_results.values():
            if t_res.type == TASK_QUIZ and "generated_questions" in t_res.metadata:
                questions = t_res.metadata["generated_questions"]
                break

    # Build Markdown table based on input questions
    if questions:
        headers = ["السؤال", "الإجابة الصحيحة"] if lang == "ar" else ["Question", "Correct Answer"]
        rows = [f"| {q['question']} | {q['correct']} |" for q in questions]
        content = f"### {headers[0]} / {headers[1]}\n| {headers[0]} | {headers[1]} |\n|---|---|\n" + "\n".join(rows)
    else:
        # Fallback if no sequential quiz input was passed
        if lang == "ar":
            content = "### جدول الإجابات النموذجية\n| السؤال | الإجابة الصحيحة |\n|---|---|\n| السؤال 1 | الخيار الأول |\n| السؤال 2 | الخيار الثاني |"
        else:
            content = "### Answers Table\n| Question | Correct Answer |\n|---|---|\n| Question 1 | Option A |\n| Question 2 | Option B |"

    return TaskResult(
        task_id=task.task_id,
        type=TASK_ANSWER_TABLE,
        status="success",
        content=content,
        citations=[Citation(chunk_id="chunk_answer_table_ref", page_number=2, score=0.90)],
        confidence=MOCK_CONFIDENCE,
        metadata={"mock": True, "consumed_quiz_questions": len(questions) > 0}
    )

async def run_key_points_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """Simulates extracting key points."""
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_KEY_POINTS,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    if lang == "ar":
        content = "### النقاط الرئيسية المستخلصة\n- النقطة الأولى والمحورية.\n- النقطة الثانية والتفصيلية.\n- النقطة الثالثة والأثر التعليمي."
    else:
        content = "### Key Takeaways\n- Primary focal point.\n- Secondary detailed point.\n- Educational outcome point."

    return TaskResult(
        task_id=task.task_id,
        type=TASK_KEY_POINTS,
        status="success",
        content=content,
        citations=[Citation(chunk_id="chunk_keypoints", page_number=3, score=0.86)],
        confidence=MOCK_CONFIDENCE,
        metadata={"mock": True}
    )

async def run_comparison_table_pipeline(task: Task, request: Any, previous_results: Optional[Dict[str, Any]] = None) -> TaskResult:
    """Simulates generating a comparison table."""
    if check_no_answer_trigger(task.query):
        return TaskResult(
            task_id=task.task_id,
            type=TASK_COMPARISON_TABLE,
            status="no_answer",
            content=NO_ANSWER_FALLBACK,
            citations=[],
            confidence=0.0,
            metadata={"mock": True}
        )

    lang = getattr(request, "language", "ar")
    if lang == "ar":
        content = "### جدول مقارنة محاكى\n| الميزة | الموضوع أ | الموضوع ب |\n|---|---|---|\n| التعريف | قيمة أ | قيمة ب |\n| الاستخدام | سياق أ | سياق ب |"
    else:
        content = "### Simulated Comparison Table\n| Feature | Topic A | Topic B |\n|---|---|---|\n| Definition | Value A | Value B |\n| Use Case | Context A | Context B |"

    return TaskResult(
        task_id=task.task_id,
        type=TASK_COMPARISON_TABLE,
        status="success",
        content=content,
        citations=[Citation(chunk_id="chunk_comparison", page_number=4, score=0.87)],
        confidence=MOCK_CONFIDENCE,
        metadata={"mock": True}
    )

# Global Registry
PIPELINE_REGISTRY: Dict[str, Any] = {
    TASK_CHAT_ANSWER: run_chat_answer_pipeline,
    TASK_EXPLAIN: run_explain_pipeline,
    TASK_SUMMARY: run_summary_pipeline,
    TASK_QUIZ: run_quiz_pipeline,
    TASK_ANSWER_TABLE: run_answer_table_pipeline,
    TASK_KEY_POINTS: run_key_points_pipeline,
    TASK_COMPARISON_TABLE: run_comparison_table_pipeline
}
